security:
  encoders:
    App\Entity\User:
      algorithm: auto

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    dupa:
      pattern: ^/api/dupa
      security: false

    register:
      pattern: ^/api/user
      security: false

    login:
      pattern: ^/api/login
      stateless: true
      anonymous: true
      json_login:
        check_path: /api/login_check
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure

    api:
      pattern: ^/api
      stateless: true
      anonymous: false
      guard:
        authenticator:
          lexik_jwt_authentication.jwt_token_authenticator

  access_control:
    - { path: ^/profile, roles: IS_AUTHORIZED_ANONYMOUSLY }
    - { path: ^/api/login, roles: IS_AUTHORIZED_ANONYMOUSLY }
    - { path: ^/api/login_check, roles: IS_AUTHORIZED_ANONYMOUSLY }
    - { path: ^/api/user, roles: IS_AUTHORIZED_ANONYMOUSLY }
    - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
